flowchart TD
    subgraph Client [Client]
        CLI[CLI<br>Aplicació per Consola]
        CLI --> |Interacció usuari| C_DAO[Client DAO<br> Gestió peticions]
        C_DAO --> C_Model[Client Model<br>Lògica local]
        C_Model --> |Dades processades| CLI
    end

    subgraph Server [Servidor]
        C_DAO --> |HTTP Request | API[Webservice Flask]
        API --> S_Model[Server Model<br>Lògica de negoci]
        S_Model --> S_DAO[Server DAO<br>Accés a dades]
        S_DAO --> DB[Base de Dades<br>MySQL ]
        DB --> S_DAO
        S_DAO --> S_Model
        S_Model --> API
        API --> |Resposta JSON| C_DAO
    end