flowchart TD
    subgraph Client [Client]
        A[CLI <br>Aplicació per consola] --> |Interaccció usuari| B[Client DAO <br> Gestió peticions]
        B-->M[Client Model <br> logica local]
        B-->|Retorna dades processades|A
    end

    subgraph Servidor [Servidor]
    B-->|Petició HTTP GET/POST| C[Webservice]
        C-->|Consulta Model| N[Server Model<br> logica del negoci]
        N-->|Consulta DAO| D[Server DAO <br> accés a dades]
        D-->|Consulta BBDD| DB[Base de dades]
        DB-->|Retornar dades|D
        D-->|Retornar obj processat| N
        N-->|Retornar resposat| C
        C-->|Resposta HTTP <br>JSON|B
    end