---
title: Diagrama de flux de la pantalla de login
---

graph TD
  A[GESTIÓ D'ENTRADES DE CINEMA ] 
  B[ Inici de sessió ]
  C[ Email: ____________________ ]
  D[ Contrasenya: _____________ ]
  E["[1] Iniciar sessió"]
  F["[2] Registrar-se"]
  G["[3] Sortir"]

  A --> B --> C --> D --> E
  E --> F
  F --> G