graph TD
    A[BENVINGUDA] --> B[LOGIN]
    B --> D[Registrar Usuari]
    B --> E[Pantalla Principal]

    E --> F[Consultar Pel·lícules]
    E --> G[Comprar Entrades]
    E --> H[Les Meves Entrades]
    E --> J[Tancar Sessió]