---
title: Diagrama de flux de la pantalla principal després del login
--- 

graph TD
  A[GESTIÓ D'ENTRADES DE CINEMA ] 
  B[Benvingut/da, nom usuari] 
  C[1-Consultar pel·lícules]
  D[2-Comprar entrades]
  E[3-Veure les meves entrades]
  F[4-Tancar sessió]

  A --> B
  B --> C
  C --> D
  D --> E
  E --> F